### ISSUE TITLE
suggestions for ope ope no mi

### ISSUE THREAD

**Issue by Rodriglas** [PixelatedW/mineminenomi#100]
Hello, i was thinking on some power for ope ope, idk the name of it and i think it does not have one, but its the one were he cuts everything, mountains and boats....
So i would be cool to have that in this mod, for exemple, cut blocks or separate them and then be able to trow them were you want, like takt.

**Comment by FGpisces** [comment]
Cleaning up threads, suggestion has been noted and we'll see how nicely we can implement it.
