### ISSUE TITLE
Advanced Rokushiki Suggestion

### ISSUE THREAD

**Issue by IsaacRelander** [PixelatedW/mineminenomi#134]
At double the doriki requirement for a rokushiki technique, it should turn into an advanced version with new abilities. 
Soru: short blink while mid-sprint.
Geppo: a second jump with a much greater cooldown. 
Tekkai: move with slowness
Shigan: multiple shots
Rankyaku: throw an X shaped attack for extra range and radius
Kami-e: Auto move to the side or back of an enemy hitting you.

**Comment by FGpisces** [comment]
The "advanced" Rokushiki will work differently to how you described it, but is already planned.

**Comment by FGpisces** [comment]
Cleaning up threads, advanced rokushiki is planned, but will only be added together with upgrades to all other race techniques.
