### ISSUE TITLE
Sorcery Clima Tact Bug?

### ISSUE THREAD

**Issue by DoritosVanCleef** [PixelatedW/mineminenomi#147]
**Describe the bug**
The Sorcery Clima Tact bekome 20 Attack Damage (From 6 to 20) 

**To Reproduce**
1. Use Fighting Style ,,Art of Weather,,
2. Take the Sorcery Clima Tact
3. Use Thunderstorm Tempo
4. The Sorcery Clima Tact have 20+ damage
5. Go to a another World The Staff have the 20+ Attack damage (or server)
6. Restart MC The Staff have now 6 Attack Damage

**Expected behavior**
I Tested the new Version 0.6.0.2 an the New Fighting Style
I Spam on the Singleplayer Map Whit the Sorcery Clima Tact Thunderstorm Tempo an then the Staff has the 20+ damage

**Screenshots**
https://prnt.sc/po1jni

**Additional context**
I Dont Know This is a Bug, gut the damage go back to 6 when you Restart MC (Sry for my Bad English, i am from Germany 11)

BR Doritos

**Comment by FGpisces** [comment]
Cleaning up threads, this issue has been fixed, thanks for reporting.
