### ISSUE TITLE
Zoan

### ISSUE THREAD

**Issue by moestrike** [PixelatedW/mineminenomi#149]
The zoan fruits are not working correctly on my aternos server the only one that works is Phoenix is there a mod im missing or is something wrong

**Comment by FGpisces** [comment]
It would help if you could provide more context, what do you mean by not working, what kind of server you're using, mod version and what other mods are being used.

**Comment by LizardlordNetwork** [comment]
I have this issue as well with the 1.7.10 version. when I try to go into any of the points then the screen goes black. I have this problem with every zoan except the phoenix and human fruit.
![before point](https://user-images.githubusercontent.com/37391037/84586877-06635f00-ae6f-11ea-9ac2-8a03e49cc5ea.png)
![after point](https://user-images.githubusercontent.com/37391037/84586883-0d8a6d00-ae6f-11ea-943e-3a7c407933c9.png)

**Comment by FGpisces** [comment]
I recommend removing Optifine if you're using it. Besides that, that issue has been fixed in the 1.14 versions of the game, so I recommend switching to that version, as we're releasing an update for that version soon and no more for 1.7.10

**Comment by FGpisces** [comment]
Cleaning up threads, was probably an issue with optifine.
