### ISSUE TITLE
Idea for Devil Fruit

### ISSUE THREAD

**Issue by shiftingrain123** [PixelatedW/mineminenomi#163]
If you can you should try and add Vander Deckens Mark Mark fruit, where you could hit them and then be able to throw items in your inventory at them or even blocks. Also you probably already thought about this, but buggy's Chop Chop fruit would be neat like if you would be immune to swords and you could shoot out your fist and stuff like that.

**Comment by FGpisces** [comment]
Cleaning up threads, both DFs are planned and will be implemented in the future.
