### ISSUE TITLE
[Suggestion] Gura Gura No Mi

### ISSUE THREAD

**Issue by SkyKingTv** [PixelatedW/mineminenomi#164]
**New Ability**
Hey so I wanted to suggest a 5th ability for the Guro Guro No Mi, where with any weapon you can focus a quake bubble on the blade. It would be just like Gekishin but a weapon is required! Maybe a short range blade beam style instead? Just an idea!

**Name Idea**
This attack is referred to loosely as Naginata Rasetsu

**Context**
https://giphy.com/gifs/quake-OomoRS1mPTZW8

**Comment by FGpisces** [comment]
Cleaning up threads, suggestion noted, wepons being implemented into df abilites will be worked on in the next update.
