### ISSUE TITLE
Game crashed completing quest at dojo with swordsmaster

### ISSUE THREAD

**Issue by OriginalChicotm** [PixelatedW/mineminenomi#165]
When I try to complete the quest the game just crashes.

**To Reproduce**
1. Go to  a dojo
2. Talk with Swordsmaster
3. Accept quest
4. Complete quest

**Expected behavior**
The quest to be complete and accept a new one

**Additional context**
I am playing on a server with friends with a lot of mods. It may be a conflict with other mods but doesn't seem to be from the crash report.

[crash-2020-02-20_02.45.17-server.txt](https://github.com/Wynd/mineminenomi/files/4230649/crash-2020-02-20_02.45.17-server.txt)

**Comment by FGpisces** [comment]
Will be fixed later, as right now, we're focusing on updating the 1.14 mod version.

**Comment by FGpisces** [comment]
Cleaning up threads, issue has been fixed.
