### ISSUE TITLE
1.14.4 0.5.1.1 yami bug

### ISSUE THREAD

**Issue by LargeChild** [PixelatedW/mineminenomi#179]
**Describe the bug**
dark matter has no cool down

**To Reproduce**
1. equip dark matter
2. spam it

**Expected behaviour**
to have a cool down 

**Additional context**
i messing around with the code when this happened so i was afraid i did this, but when i downloaded a fresh unaltered version from curseforge it had the same bug

**Comment by Wynd** [comment]
Fixed
