### ISSUE TITLE
Idea For Devil Fruit Suggestion 

### ISSUE THREAD

**Issue by WolfX12** [PixelatedW/mineminenomi#180]
Add Kaido's devil fruit and his mace. He should have df abilities while he is not transformed and while he is transformed. Like the same ability does something different when he is in human form or dragon form.

**Comment by FGpisces** [comment]
Cleaning up threads, we're adding devil fruits only after the Arc they're in have finished, so Kaido's df will need to wait a bit longer, we'll focus on the older dfs first.
