### ISSUE TITLE
Class/Haki Suggestion

### ISSUE THREAD

**Issue by IsaacRelander** [PixelatedW/mineminenomi#183]
Each class should have its own path for haki allowing more power in their fighting style.

**Swordsmen**: Imbuing should continuously grow in power with exp allowing further damage while normal imbuing should turn into a generic damage boost to held coated weapons. 
**Brawler**: Fullbody haki should be brawler only. Should also get a quest to punch many stones to gain further damage with fists. 
**Sniper**: A imbuing path that instead of boosting damage, boosts range in which the buso stays on the bullet or arrow.

**Comment by FGpisces** [comment]
Cleaning up threads, suggestion noted.
