### ISSUE TITLE
Config log suggestion

### ISSUE THREAD

**Issue by E-Op** [PixelatedW/mineminenomi#185]
Have you thought about making it so that you can change the spawn rate of pirates, marines and bandits with the config?
Or does that already exist and im just blind? Love the mod btw!

**Comment by Wynd** [comment]
Yeah I'll make a new patch friday (0.6.2.2) that will contain a bunch of bug fixes and some missing config options

**Comment by E-Op** [comment]
Ah cool, I'll look forward to it!
