### ISSUE TITLE
Hie Hie no Mi abilities not entirely working

### ISSUE THREAD

**Issue by bugSandwich** [PixelatedW/mineminenomi#186]
When using Ice Age near water, it does not freeze. The ground and mobs still freeze though (except flying mobs like phantoms).
Ice Avalanche does not appear to work and almost never damages mobs. The animation occurs above them, but nothing happens to mobs, even when they are directly underneath and unobscured.

**Comment by Wynd** [comment]
Fixed both of them for today's patch

**Comment by bugSandwich** [comment]
That was fast!
