### ISSUE TITLE
Medic Medication Suggestion

### ISSUE THREAD

**Issue by IsaacRelander** [PixelatedW/mineminenomi#187]
**Band-Aid**: 1 Wool to craft 4 band-aids, heal 4 hearts instantly then goes on cd for 4 seconds. 
**Medical Powder**: 1 Dandelion and 1 Cornflower to craft 2 medical powder. 
- _Medicine_: Mix powder with a bottle of water to create a paste you can place on yourself to heal for 20-40 hearts over time. Adding sugar and glowstone can increase the amount of healing or the length of the heal. 

**Doping:** 1 Poppy and 1 Oxeye Daisy to craft 1 drug, heal 10 hearts instantly and grant speed and strength for 12 seconds. After the drug wears off get weakness for 10 seconds. Increase length with redstone.

**Comment by FGpisces** [comment]
Cleaning up threads, suggestion noted.
