### ISSUE TITLE
BUG : Camera get lower than it should when sneaking.

### ISSUE THREAD

**Issue by SpeedsArrow** [PixelatedW/mineminenomi#188]
Hello, sorry to disturb you.

The bug comes when I press the sneak button, the camera is lower than one block tall.
![2020-07-24_19 10 21](https://user-images.githubusercontent.com/24204749/88417023-7dcacd80-cde1-11ea-9a10-bfbbc40fee0f.png)
![2020-07-24_19 10 34](https://user-images.githubusercontent.com/24204749/88417030-802d2780-cde1-11ea-89cf-ff0d761e4e42.png)

I took two screenshots, one where I'm standing and the other where I'm sneaking. 
This bug happens in both creative and survival.
I dont use any other mod than mine mine no mi 0.6.2.1 (same issue with version 0.6.2.2).

Have a good day.

**Comment by frostfire50** [comment]
That’s not a bug that’s normal minecraft.

**Comment by SpeedsArrow** [comment]
No it isn't. Minecraft camera isn't this low when sneaking.

**Comment by frostfire50** [comment]
opps

**Comment by Wynd** [comment]
This was fixed but I don't remember if the fix was in current 0.6.2.3 or in the upcoming 0.6.3...
