### ISSUE TITLE
Haki + Devilfruit

### ISSUE THREAD

**Issue by strictlee** [PixelatedW/mineminenomi#190]
Can you have haki and devilfruit at the same time and if so how?
pls help

**Comment by Sepinula** [comment]
Yes you can so there is a command /doriki + 10000 something like that if that isn't the command just type /doriki and follow the example there, you can also get doriki by killing the captain from what i remember

**Comment by Wynd** [comment]
Haki is trained via....well...playing the game, killing enemies with swords will give you imbuing haki exp, if you kill them with a punch it'll give hardening haki exp and by simply fighting stuff and not dying you'll get observation haki exp...eventually you'll unlock them, there's 5 types of haki + haoshoku haki. Worth noting is that observation will become incredibly hard to get if you eat a logia...as you won't be able to get damaged from that point on.
