### ISSUE TITLE
Source Edit 

### ISSUE THREAD

**Issue by Sepinula** [PixelatedW/mineminenomi#191]
**Describe the bug**
So i saw your mod was open sourced i wanted to get some attacks and i added them but when "build" the mod get it in java i open it and i go to a single player it says i do not have access to this version
**Expected behavior**
i thought i could just edit your mod and there wouldn't be any problem at all

**Screenshots**
 https://prnt.sc/u0izqi

**Additional context**
the attack i added was red hawk 

Add/Send me on discord anyone knows how to resolve this pls rarely use github Sepinula#6971 but will come here to check if the issue is resolved :D

**Comment by Wynd** [comment]
I know we've talked via Discord but if anybody else encounters this issue:
Go into APIConfig and change the BUILD_MODE to FINAL or simply open the game in debug mode.

**Comment by Sepinula** [comment]
Hello so i did resolve the issue and it didn't have to change the BUILD_MODE to Final i had to change a whole file

**Comment by Sepinula** [comment]
also i did add my ability and somethings 👍

**Comment by Wynd** [comment]
Again...just because you don't know how variables work doesn't mean it's not the right solution.
Changing BUILD_MODE to Final _IS_ is the correct solution aside from simply booting in debug mode.
