### ISSUE TITLE
SUGGESTION FOR WEAPONS

### ISSUE THREAD

**Issue by MXlordsMapone123** [PixelatedW/mineminenomi#192]
> make each weapon have different skills
> each skill of each weapon can be unlocked with an xp system that evolves only the weapon the player uses
> make a remaster of the weapons and put them 3d

**Comment by FGpisces** [comment]
Cleaning up threads, unique abilities for some weapons will be added next update, some armor pieces like Sniper goggles and Don krieg's armor already have that implementation.
