### ISSUE TITLE
Crash due to an entitie

### ISSUE THREAD

**Issue by Volxix** [PixelatedW/mineminenomi#193]
**Describe the bug**
everytime i hit a marine the game gets corrutped
**To Reproduce**
1. Go to an marine and hit him and the world will get corrupted
2. Click on 
ticking entity
**Expected behavior**
it to take damage and not break
**Screenshots**
![image](https://user-images.githubusercontent.com/71120210/92880907-5f0ead80-f406-11ea-9df4-8c22747a6957.png)

**Additional context**
i am playing on 1.14,4 with version 0.6.2 with forge 1.14.4 28.2.23 i will try other versions of forge

**Comment by Wynd** [comment]
Fixed in 0.6.2.3
