### ISSUE TITLE
Boss Suggestions

### ISSUE THREAD

**Issue by IsaacRelander** [PixelatedW/mineminenomi#194]
I know Wynd has most bosses planned and even a few models made, this list is just a few odd characters from the early one piece years that can be added soon in the boss system. 
Axe-Hand Morgan
Cabaji and Mohji: I expect Buggy to be added in but his two main sidekicks should also be added. 
Koushirou: Could be an interesting boss for swordsmen wanting to fight a final master. 
Fullbody: "Double Iron-Fist" marine dude, would be a decent captain level fight. 
Jango: He would be a marine but still be able to "hypnotize" you. 
Kuro
Bogard: He's Garps right-hand man so he's around vice-rear admiral level at least.
Dorry & Brogy: A couple of giant fights, you only fight one at a time but you always find them together.
Hina: A girl with an ex fruit, seems easy enough.  
Gan Fall
That's as far as I'll go for now :P

**Comment by adrian200145** [comment]
I think iy would be cool to have a kaido dragon fight, for some distant feature, maybe change the end by onigashima, i dont know something like that would be cool.

**Comment by FGpisces** [comment]
Cleaning up threads, bosses are planned and will be gradually implemented in the upcomin updates, the recent one already has three (Gin, Don Krieg, Morgan)
