### ISSUE TITLE
Suggestions for fruits

### ISSUE THREAD

**Issue by Blu44** [PixelatedW/mineminenomi#196]
I don't know if I'm writing a suggestion or a bug so.. for fruits already out:
1) yami yami no mi  There is the ability that allows the wielder to absorb damage, like, if you're dying from a negative effect (not mob attacks) like fire, you can take away the effect by absorbing it. Like ace vs blackbeard
2) for the Kage kage no mi the skill that creates a brick bat wall (or how to spell them) like the bari bari no mi wall but with kage fruit.
3) for gura and mera or other fruit they increase the damage by improving weapon (like the the mera can set it on fire even if with all the other moves it would be a bit useless and for the gura it simply does more damage and a small explosion

**Comment by FGpisces** [comment]
Suggestion noted, closing thread.
