### ISSUE TITLE
Ticking Entity crash with marine captain.

### ISSUE THREAD

**Issue by frostfire50** [PixelatedW/mineminenomi#198]
Describe the bug
You crash when you get hit directly by the tempest kick

**To Reproduce**
1. Find a Marine captain
2. Go far enough away for him to shoot the tempest kick
3. Let it hit you directly
4. Then you get the ticking entity crash.

**Expected behavior**
To take damage from the attack

**Screenshots**

**Additional context**
Here’s the crashlog https://hastebin.com/joyanesubi.yaml

**Comment by FGpisces** [comment]
Was fixed, should not happen anymore.
