### ISSUE TITLE
[Latest version] Weird stuff with the structure generation and chest loots

### ISSUE THREAD

**Issue by Erenussocrates** [PixelatedW/mineminenomi#209]
I wanted to test it so I started a creative world to see how long it would take me to find a golden chest, (it used to not last overly long for the previous versions). On this version, after flying over some 20,000 blocks from the spawn, I couldn't get a single Iron Box to appear in the loot of a big ship, a big bandit hideout or a big marine base. As a matter of fact, even the lowest tier wooden boxes themselves are quite rare too. On one freak of a chance (it might even be a related bug), I've found two golden boxes and one wooden box in the loot of a single big marine ship. Other than that, nor the same chance nor nothing in between happened ever again, in fact even the wooden boxes are so rare and the other loot inside the ships are so miniscule that it would make me not want to bother with raiding them anymore on a survival playthrough. The captain's chests inside the big marine bases especially hold absolutely useless junk, most commonly raw porkchops, while they used to be the most reliable source to get higher tier devil fruit boxes in the past.

On a related note, the generation of big marine base structures seem to be messed up every time, without exception. It always has some parts of the building missing. The same also happens for the big bandit hideouts as well, albeit not as common, some of the rooms down below are completely blocked off by stone and they don't seem to have generated at all, this can happen for the treasure room, or the general area where the smelters sit. Also while the sky islands used to exist in the previous versions, I couldn't spot a single sky island at all either.

Also I've noticed that you might have added wooden devil fruit boxes on some of the vanilla loots, I've encountered a wooden box once or twice in a sunken ship structure and an underwater ruin, I wonder if the same applies for some of the other vanilla structures as well. Your guide might need a comprehensive update on where we could find what, including the vanilla locations.

**Comment by FGpisces** [comment]
Already answered on Curse, closing the issue here.
