### ISSUE TITLE
Devil fruits not working

### ISSUE THREAD

**Issue by Limastron** [PixelatedW/mineminenomi#212]
Eat any of the devil fruits don't give you any abilities,  just the water weakness.

I have installed the last version and other 4 but they all have the same bug.

I want to know if this will be fixed or it's me making a grave mistake

**Comment by FGpisces** [comment]
Press R (by default) to open the stats UI, press the 'Abilities' button, select any slot you wish to add an ability in (a blue outline will appear), select any ability from the above panel, after that quit the UI and press ALT for the combat UI to show up.
