### ISSUE TITLE
Mine mine no mi failed to load correctly

### ISSUE THREAD

**Issue by eustacethemad** [PixelatedW/mineminenomi#216]
I downloaded the mod today, I've did all the steps correct and even reinstalled everything but I still get this error 
[latest.log](https://github.com/PixelatedW/mineminenomi/files/6079672/latest.log)   

This is my log as you can see

![Screenshot_85](https://user-images.githubusercontent.com/80010782/109883305-47650300-7c8c-11eb-8a77-6654f73ae9f5.png)

and this is the error page, Can you guys give me an instruction if I'm doing something wrong Java is the latest version and I use forge-1.14.4-28.2.23

**Comment by eustacethemad** [comment]
And if it's possible can I get a link to your discord server.

**Comment by Wynd** [comment]
Change your windows language to anything but turkish, restart your pc, now it'll work.
Discord link: [https://discord.com/invite/CYK9xs8](https://discord.com/invite/CYK9xs8)
