### ISSUE TITLE
Suggestion about DF's

### ISSUE THREAD

**Issue by AdmiralSakazuki** [PixelatedW/mineminenomi#68]
Ok so are you guys planning on adding Katakuri's Mochi Mochi no mi , but how will  it work like it is a paramecia but Katakuri uses it like a logia because the attacks go through it's body, that is all due to Kenbunshoku Haki but what I will want to see is that at the start if you consume the DF you cant be like a "Logia" but once you unlock Ken haki the you can be like a logia like user but paramecia do you understand me xd? so that is my suggestion for Katakuri's DF and thank you for reading!

**Comment by FGpisces** [comment]
Yes, we're planning to, but not that soon. Nice suggestion, the dodging aspect of it will definitely be influenced by the player unlocking Ken haki.

**Comment by FGpisces** [comment]
Cleaning up threads, will be implemented like that, noted it, so I'm closing this thread.
