### ISSUE TITLE
Bug Ori Ori no mi, Cage's bottom and top

### ISSUE THREAD

**Issue by Inovactio** [PixelatedW/mineminenomi#93]
**Describe the bug**
I don't know if i can called it a bug or a possible improvement. With the Ori Ori fruit the bars generate acts as the minecraft iron bars. Then it is possible to pass between its.
Also, bars are not generate where there is grass, or flowers (snow too).

**To Reproduce**
1. Eat the Ori Ori no mi.
2. Use the Great Cage abitity in air for the first bug.
3. Use the Great Cage abitity near from grass for the second one.

**Expected behavior**
Normally you can't escape from thecage, then the block at the bottom and at the top should be impassable.
And the generate Cage should be generate instead of grass, flowers or anything else that is not a solid block.

**Screenshots 1st bug**

![2019-04-07_14 30 01](https://user-images.githubusercontent.com/49309023/55683622-06e69880-5942-11e9-8fd8-22283c75aee7.png)

![2019-04-07_14 30 08](https://user-images.githubusercontent.com/49309023/55683633-18c83b80-5942-11e9-8720-68178b187f0d.png)

**Screenshots 2nd bug**

![2019-04-07_14 29 49](https://user-images.githubusercontent.com/49309023/55683620-01894e00-5942-11e9-811d-36355b9562a8.png)

![2019-04-07_14 42 59](https://user-images.githubusercontent.com/49309023/55683733-790bad00-5943-11e9-9f82-46fa066f0dee.png)

**Additional context**
I also sugget to change the ability to act as the bari bari no mi's ability. A kind of set/unset of the blocks.
To fix the 1st bug, you should change the bars generate at the bottom and at the top by a new block (like Cage block) which act as the bars but cannot be passable. Or change the cage bars to be a new kind of block which cover the top and the bottom of the cage.

(I have test bari bari no mi for the 2nd bug and it works with the grass and the flowers by deleting these, but with the snow it doesnt work and the snow is still here.)
![2019-04-07_14 52 52](https://user-images.githubusercontent.com/49309023/55683864-d8b68800-5944-11e9-90a5-c0dca6dcb199.png)

**Comment by FGpisces** [comment]
Cleaning up threads, Ori was removed in 1.14 versions and will be reworked before added.
