### ISSUE TITLE
Devil fruit suggestion 

### ISSUE THREAD

**Issue by TheLoramir** [PixelatedW/mineminenomi#96]
An interesting fruit to have in the mod could be the Shiro Shiro no Mi, Capone gang Bege's devil fruit, I do realized that that particular devil fruit would be especially difficult considering the Big Father ability, but I think you could do it! And btw This is literally the best one piece mod out there thank you for gracing us with it (sorry to go all Bartolomeo on you there)

**Comment by Wynd** [comment]
Thanks, I believe shiro shiro no mi is planned but yes it will be hard to add, and as such don't expect it to be added soon..

**Comment by FGpisces** [comment]
Cleaning up threads, DFs are planned and will be added.
